name: wysiwyg_editor
description: A Detailed Rich Text Editor for Flutter
version: 1.3.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  random_string: ^2.3.1
  flutter_quill: ^10.7.6
  flutter_quill_extensions: ^10.7.6
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
