name: wysiwyg_flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 3.2.0

topics:
  - widgets
  - widget
  - rich-text-editor

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Dart Packages
  http: ^1.2.0
  path: ^1.8.3
  meta: ^1.10.0
  universal_html: ^2.2.4
  cross_file: ^0.3.3+6

  wysiwyg_flutter_quill: 3.1.0
  photo_view: ^0.15.0

  # Plugins
  url_launcher: ^6.2.1
  gal: ^2.3.0
  gal_linux: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
