name: wysiwyg_quill_native_bridge
description: "An internal plugin for flutter_quill package to access platform-specific APIs"
version: 2.0.0
homepage: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge
repository: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge
issue_tracker: https://github.com/FlutterQuill/quill-native-bridge/issues
documentation: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge

platforms:
  android:
  ios:
  macos:
  web:
  linux:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wysiwyg_quill_native_bridge_android: ^2.0.0
  quill_native_bridge_platform_interface: ^0.0.1-dev.4
  quill_native_bridge_web: ^0.0.1-dev.4
  quill_native_bridge_windows: ^0.0.1-dev.3
  quill_native_bridge_linux: ^0.0.1-dev.3
  quill_native_bridge_ios: ^0.0.1-dev.4
  quill_native_bridge_macos: ^0.0.1-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: quill_native_bridge_android
      ios:
        default_package: quill_native_bridge_ios
      macos:
        default_package: quill_native_bridge_macos
      web:
        default_package: quill_native_bridge_web
      windows:
        default_package: quill_native_bridge_windows
      linux:
        default_package: quill_native_bridge_linux
