name: wysiwyg_quill_native_bridge_android
description: "Android implementation of the quill_native_bridge plugin."
version: 2.0.0
homepage: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_android
repository: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_android
issue_tracker: https://github.com/FlutterQuill/quill-native-bridge/issues?q=is%3Aissue+is%3Aopen+label%3A%22platform-android%22
documentation: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_android

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quill_native_bridge_platform_interface: ^0.0.1-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^22.4.1

flutter:
  plugin:
    implements: quill_native_bridge
    platforms:
      android:
        package: dev.flutterquill.quill_native_bridge
        pluginClass: QuillNativeBridgePlugin
        dartPluginClass: QuillNativeBridgeAndroid
