name: wysiwyg_flutter_quill
description: "A rich text editor built for Android, iOS, Web, and desktop platforms. It's the WYSIWYG editor and a Quill component for Flutter."
version: 1.0.0


topics:
  - widgets
  - widget
  - rich-text-editor
  - quill


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Dart Packages
  intl: ^0.19.0
  dart_quill_delta: ^10.0.0
  collection: ^1.17.0
  quiver: ^3.2.1
  equatable: ^2.0.5
  meta: ^1.10.0
  html: ^0.15.4

  flutter_colorpicker: ^1.1.0

  # For converting HTML to Quill delta
  flutter_quill_delta_from_html: ^1.4.1
  markdown: ^7.2.1
  charcode: ^1.3.1

  # Plugins
  url_launcher: ^6.2.4
  flutter_keyboard_visibility_temp_fork: ^0.1.1
  wsiwyg_quill_native_bridge: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_quill_test: ^10.0.0
  test: ^1.24.3

  # For scripts only
  yaml_edit: ^2.2.1
  yaml: ^3.1.2
  http: ^1.2.1

  path: any
flutter:
  uses-material-design: true
  generate: true
